# Generated by Django 2.2.24 on 2022-10-19 15:48

from django.db import migrations


def fill_new_building(apps, _):
    for flat in apps.get_model('property', 'Flat').objects.all():
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]
