# Generated by Django 2.2.24 on 2022-10-19 15:48

from django.db import migrations, models


def fill_new_building(apps, _):
    apps.get_model('property', 'Flat').objects.update(new_building=models.F('construction_year') >= 2015)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building),
    ]
