# Generated by Django 4.1.2 on 2022-10-20 07:19

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone(apps, _):
    for flat in apps.get_model('property', 'Flat').objects.all():
        try:
            parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber)
        except phonenumbers.phonenumberutil.NumberParseException:
            continue

        if not phonenumbers.is_valid_number(parsed_phonenumber):
            continue

        if not phonenumbers.is_possible_number(parsed_phonenumber):
            continue

        flat.owner_pure_phone = phonenumbers.format_number(
            parsed_phonenumber,
            phonenumbers.PhoneNumberFormat.INTERNATIONAL
        )
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone),
    ]
