# Generated by Django 4.1.2 on 2022-10-20 07:53

from django.db import migrations


def fill_owners_data(apps, _):
    for flat in apps.get_model('property', 'Flat').objects.all():
        owner, created = apps.get_model('property', 'Owner').objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )

        owner.flats.add(flat)
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_flat_owner_pure_phone_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners_data)
    ]
